name: "Tests"

on:
  pull_request:
  push:
    branches:
      - main

env:
  fail-fast: true
  PHPUNIT_FLAGS: "-v"
  SYMFONY_PHPUNIT_DIR: "$HOME/symfony-bridge/.phpunit"
  SYMFONY_DEPRECATIONS_HELPER: 7

permissions:
  contents: read

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1', '8.2']

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3

      - name: "Install PHP with extensions"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          extensions: "intl, mbstring, pdo_sqlite"
          php-version: ${{ matrix.php-version }}
          tools: composer:v2

      - name: "Add PHPUnit matcher"
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - uses: "ramsey/composer-install@v3"

      - name: "Install PHPUnit"
        run: vendor/bin/simple-phpunit install

      - name: "PHPUnit version"
        run: vendor/bin/simple-phpunit --version

      - name: "Run tests"
        run: vendor/bin/simple-phpunit ${{ env.PHPUNIT_FLAGS }}
